<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>14</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../Common/ComSharp/**/*.cs" LinkBase="ComSharp" />
    <Compile Include="../Farkle/Obsoletions.cs" LinkBase="Farkle" />
    <Compile Include="../Farkle/Diagnostics/DiagnosticSeverity.cs" LinkBase="Farkle" />
    <Compile Include="../Farkle/Compatibility/EmbeddedAttribute.cs" LinkBase="Farkle/Compatibility" />
    <!-- <ProjectReference Include="..\Farkle\Farkle.csproj" /> -->
    <PackageReference Include="Microsoft.Build.Utilities.Core" />
    <PackageReference Include="Mono.Cecil" />
  </ItemGroup>
</Project>
