// Copyright © Theodore Tsirpanis and Contributors.
// SPDX-License-Identifier: MIT

using System.Runtime.InteropServices;
using Mono.Cecil;
using Mono.Cecil.Cil;
using Mono.Cecil.Rocks;
using Sigourney;

namespace Farkle.Tools.Precompiler.Weaver;

public sealed class PrecompilerWeaver
{
    private const string MangledNamePrefix = "$Farkle$<>";

    private readonly KnownMembers _knownMembers;

    private static readonly AssemblyNameReference _weaverAssemblyName = GetWeaverAssemblyName();

    private static AssemblyNameReference GetWeaverAssemblyName()
    {
        var name = typeof(PrecompilerWeaver).Assembly.GetName();
        return new(name.Name, name.Version);
    }

    private PrecompilerWeaver(ModuleDefinition module, IReadOnlyCollection<AssemblyReference> references)
    {
        _knownMembers = new(references, module);
    }

    private static TypeReference GetOrCreateRvaFieldSizeType(TypeDefinition baseType, int size)
    {
        var module = baseType.Module;
        switch (size)
        {
            case 1: return module.TypeSystem.Byte;
            case 2: return module.TypeSystem.UInt16;
            case 4: return module.TypeSystem.UInt32;
            case 8: return module.TypeSystem.UInt64;
        }

        string name = $"{MangledNamePrefix}StaticArrayInitTypeSize=${size}";
        TypeDefinition? existingType = baseType.NestedTypes.First(x => x.Name == name);
        if (existingType is not null)
        {
            return existingType;
        }
        var type = new TypeDefinition("", name, TypeAttributes.NestedPrivate)
        {
            IsValueType = true,
            ClassSize = size
        };
        baseType.NestedTypes.Add(type);
        return type;
    }

    private static string GetMangledGrammarFieldName(PrecompiledGrammar grammar)
    {
        const string Prefix = $"{MangledNamePrefix}GrammarData";
        return grammar.Key is { } k ? $"{Prefix};Key={k}" : Prefix;
    }

    private CustomAttribute CreateGeneratedCodeCustomAttribute(AssemblyNameReference assemblyName)
    {
        var ca = new CustomAttribute(_knownMembers.GeneratedCodeAttribute_Ctor);
        ca.ConstructorArguments.Add(new(_knownMembers.String, assemblyName.Name));
        ca.ConstructorArguments.Add(new(_knownMembers.String, assemblyName.Version?.ToString()));
        return ca;
    }

    private CustomAttribute CreatePrecompiledGrammarCustomAttribute(PrecompiledGrammar grammar)
    {
        var ca = new CustomAttribute(_knownMembers.PrecompiledGrammarAttribute_Ctor);
        if (grammar.Key is { } key)
        {
            ca.Properties.Add(new("Key", new(_knownMembers.String, key)));
        }
        return ca;
    }

    private FieldDefinition EmitGrammarRvaField(TypeDefinition baseType, PrecompiledGrammar grammar)
    {
        var name = GetMangledGrammarFieldName(grammar);
        const FieldAttributes fieldAttributes = FieldAttributes.Private | FieldAttributes.Static | FieldAttributes.InitOnly;
        var fieldType = GetOrCreateRvaFieldSizeType(baseType, grammar.GrammarFile.Length);
        var field = new FieldDefinition(name, fieldAttributes, fieldType)
        {
            InitialValue = ImmutableCollectionsMarshal.AsArray(grammar.GrammarFile)
        };
        field.CustomAttributes.Add(CreatePrecompiledGrammarCustomAttribute(grammar));
        // The field was emitted by Farkle.Tools.Precompiler, but the field's data were generated by Farkle.
        field.CustomAttributes.Add(CreateGeneratedCodeCustomAttribute(_knownMembers.Farkle.Name));
        baseType.Fields.Add(field);
        return field;
    }

    private void Weave(ModuleDefinition module, IReadOnlyCollection<PrecompiledGrammar> grammars)
    {
        foreach (var grammar in grammars)
        {
            var inputMethod = (MethodDefinition)module.LookupToken(grammar.InputMethodMetadataToken);
            var baseType = inputMethod.DeclaringType;

            var grammarField = EmitGrammarRvaField(baseType, grammar);

            foreach (var x in grammar.OutputMethods)
            {
                var outputMethod = (MethodDefinition)module.LookupToken(x.MetadataToken);
                var body = new MethodBody(outputMethod);
                var il = body.GetILProcessor();

                switch (x.Type)
                {
                    case OutputType.Grammar:
                        EmitLoadGrammarPreamble();
                        il.Emit(OpCodes.Call, _knownMembers.PrecompilerEntryPoints_LoadGrammar);
                        il.Emit(OpCodes.Ret);
                        break;
                    case OutputType.CharParser or OutputType.CharParserSyntaxChecker:
                        bool syntaxCheck = x.Type == OutputType.CharParserSyntaxChecker;
                        var parserOutputType = outputMethod.ReturnType.GenericParameters[0];
                        TypeReference delegateFactoryType;
                        MethodDefinition factoryMethodDef;
                        if (!syntaxCheck)
                        {
                            // The output method returns CharParser<T>. We want to construct a Func<IGrammarBuilder<T>>
                            // to pass to Farkle.
                            var grammarBuilderType = _knownMembers.IGrammarBuilder_1.MakeGenericInstanceType(parserOutputType);
                            delegateFactoryType = _knownMembers.Func_1.MakeGenericInstanceType(grammarBuilderType);
                            factoryMethodDef = _knownMembers.PrecompilerEntryPoints_LoadCharParserSyntaxChecker;
                        }
                        else
                        {
                            delegateFactoryType = _knownMembers.Func_1.MakeGenericInstanceType(_knownMembers.IGrammarBuilder);
                            factoryMethodDef = _knownMembers.PrecompilerEntryPoints_LoadCharParser;
                        }
                        EmitLoadGrammarPreamble();
                        // TODO: If we are making a syntax checker, use MetadataUpdater.IsSupported if it exists,
                        // to skip constructing the delegate.
                        il.Emit(OpCodes.Ldftn, inputMethod);
                        il.Emit(OpCodes.Ldnull);
                        il.Emit(OpCodes.Newobj, delegateFactoryType.GetDelegateConstructor());
                        il.Emit(OpCodes.Call, factoryMethodDef.MakeGenericMethod([parserOutputType]));
                        il.Emit(OpCodes.Ret);
                        break;
                    default:
                        throw new ArgumentOutOfRangeException(null, x.Type, "Invalid output method type.");
                }

                outputMethod.Body = body;
                outputMethod.CustomAttributes.Add(CreateGeneratedCodeCustomAttribute(_weaverAssemblyName));

                void EmitLoadGrammarPreamble()
                {
                    il.Emit(OpCodes.Ldsflda, grammarField);
                    il.Emit(OpCodes.Ldc_I4, grammar.GrammarFile.Length);
                    il.Emit(OpCodes.Ldtoken, grammarField.DeclaringType);
                }
            }
        }
    }

    public static void Weave(ModuleDefinition module, IReadOnlyCollection<AssemblyReference> references, IReadOnlyCollection<PrecompiledGrammar> grammars)
    {
        var weaver = new PrecompilerWeaver(module, references);
        weaver.Weave(module, grammars);
    }
}
