version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      # Do not automatically update dependencies that use version $(SystemOobVersion) in Directory.Packages.props.
      - dependency-name: "System.Collections.Immutable"
