version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      test:
        patterns:
          - "Expecto"
          - "Expecto.*"
          - "Microsoft.NET.Test.Sdk"
          - "Microsoft.Testing.*"
          - "NUnit"
          - "NUnit3TestAdapter"
          - "NUnit.*"
          - "YoloDev.Expecto.TestSdk"
    ignore:
      # Do not automatically update dependencies that use version $(SystemOobVersion) in Directory.Packages.props.
      - dependency-name: "System.Collections.Immutable"
