image: Visual Studio 2017
init:
  - git config --global core.autocrlf input
build_script:
  - cmd: build.cmd target CI
test: off
artifacts:
- path: docs.zip
- path: bin/*.nupkg
version: 3.1.0.{build}
