<Project>
  <Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)../'))" Condition="'' != $([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)../'))" />
  <PropertyGroup Condition="'$(GITHUB_ACTIONS)' != ''">
    <!--TODO: Add back when it gets MTP support.-->
    <!--<VSTestLogger>GitHubActions</VSTestLogger>-->
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage" />
    <!--<PackageReference Include="GitHubActionsTestLogger" />-->
  </ItemGroup>
</Project>
