// Copyright © Theodore Tsirpanis and Contributors.
// SPDX-License-Identifier: MIT

using System.ComponentModel;
using System.Diagnostics.CodeAnalysis;
using System.Reflection;
using System.Reflection.Metadata;
using ComSharp;
using Farkle.Builder;
using Farkle.Builder.Precompiler;
using Farkle.Grammars;
using Farkle.HotReload;

namespace Farkle.Runtime;

/// <summary>
/// Contains methods that get called by code generated by the precompiler.
/// This class should not be directly used by user code.
/// </summary>
[EditorBrowsable(EditorBrowsableState.Never)]
public static class PrecompilerEntryPoints
{
    /// <summary>
    /// Loads a precompiled <see cref="Grammar"/>.
    /// </summary>
    /// <param name="data">A pointer to the grammar's data.</param>
    /// <param name="length">The grammar data's length.</param>
    /// <param name="containingType">A handle to the type where the grammar is declared.</param>
    /// <remarks>
    /// The returned grammar will contain a reference to <paramref name="containingType"/>,
    /// and prevent unloading it.
    /// </remarks>
    public static unsafe Grammar LoadGrammar(byte* data, int length, RuntimeTypeHandle containingType)
    {
        if (length != 0)
        {
            ArgumentNullException.ThrowIfNull(data);
            ArgumentOutOfRangeException.ThrowIfNegative(length);
        }
        if (containingType.Value == 0)
        {
            ThrowHelpers.ThrowArgumentNullException(nameof(containingType));
        }

        // Do not perform content validation; the grammar is from a loaded assembly,
        // which is presumed to be trusted.
        return new Grammar.PrecompiledGrammar(data, length, containingType);
    }

    /// <summary>
    /// Creates a <see cref="CharParser{T}"/> from a precompiled grammar.
    /// </summary>
    /// <typeparam name="T">The type of objects the parser produces in case of success.</typeparam>
    /// <param name="data">A pointer to the grammar's data.</param>
    /// <param name="length">The grammar data's length.</param>
    /// <param name="containingType">A handle to the type where the grammar is declared.</param>
    /// <param name="precompilerInputFunction">A delegate to the grammar's corresponding method that
    /// was marked with <see cref="PrecompilerInputAttribute"/>.</param>
    /// <remarks>
    /// The returned parser will contain a reference to <paramref name="containingType"/>,
    /// and prevent unloading it.
    /// </remarks>
    public static unsafe CharParser<T> LoadCharParser<T>(byte* data, int length, RuntimeTypeHandle containingType,
        Func<IGrammarBuilder<T>> precompilerInputFunction)
    {
        if (length != 0)
        {
            ArgumentNullException.ThrowIfNull(data);
            ArgumentOutOfRangeException.ThrowIfNegative(length);
        }
        if (containingType.Value == 0)
        {
            ThrowHelpers.ThrowArgumentNullException(nameof(containingType));
        }
        ArgumentNullException.ThrowIfNull(precompilerInputFunction);

        var grammar = LoadGrammar(data, length, containingType);
        var semanticProvider = precompilerInputFunction().BuildSemanticProvider();
        var result = CharParser.Create(grammar, semanticProvider);

        if (MetadataUpdater.IsSupported)
        {
            var containingTypeObj = Type.GetTypeFromHandle(containingType)!;
            var initialParser = !MetadataUpdatableManager.IsMaybeReloaded(containingTypeObj) ? result : null;
            result = MetadataUpdatableParser.Create(containingTypeObj, ParserFactory, initialParser);
            CharParser<T> ParserFactory()
            {
                var builderOptions = new BuilderOptions();
                // Extract build options from the attribute; it should always exist, unless this method was manually
                // called. We have to get the attribute every time, because it might have changed in the reload.
                if (precompilerInputFunction.Method.GetCustomAttribute<PrecompilerInputAttribute>() is { } attr)
                {
                    builderOptions.UpdateFrom(attr);
                }
                var builder = precompilerInputFunction();
                return builder.Build(builderOptions);
            }
        }

        return result;
    }

    /// <summary>
    /// Creates a syntax-checking <see cref="CharParser{T}"/> from a precompiled grammar.
    /// </summary>
    /// <typeparam name="T">The type of objects the syntax checker will return in case of success.
    /// Must be a reference type and usually it is <see cref="object"/>
    /// or <see cref="T:Microsoft.FSharp.Core.Unit"/>.</typeparam>
    /// <param name="data">A pointer to the grammar's data.</param>
    /// <param name="length">The grammar data's length.</param>
    /// <param name="containingType">A handle to the type where the grammar is declared.</param>
    /// <param name="precompilerInputFunction">A delegate to the grammar's corresponding method that
    /// was marked with <see cref="PrecompilerInputAttribute"/>. This parameter is optional and can
    /// be <see langword="null"/>, in which case some features such as Hot Reload integration will
    /// not be enabled.</param>
    /// <remarks>
    /// The returned parser will contain a reference to <paramref name="containingType"/>,
    /// and prevent unloading it.
    /// </remarks>
    /// <seealso cref="CharParser.CreateSyntaxChecker{T}"/>
    public static unsafe CharParser<T?> LoadCharParserSyntaxChecker<T>(byte* data, int length, RuntimeTypeHandle containingType,
        Func<IGrammarBuilder>? precompilerInputFunction) where T : class?
    {
        if (length != 0)
        {
            ArgumentNullException.ThrowIfNull(data);
            ArgumentOutOfRangeException.ThrowIfNegative(length);
        }
        if (containingType.Value == 0)
        {
            ThrowHelpers.ThrowArgumentNullException(nameof(containingType));
        }

        var grammar = LoadGrammar(data, length, containingType);
        var result = CharParser.CreateSyntaxChecker<T>(grammar);

        if (MetadataUpdater.IsSupported && precompilerInputFunction is not null)
        {
            var containingTypeObj = Type.GetTypeFromHandle(containingType)!;
            var initialParser = !MetadataUpdatableManager.IsMaybeReloaded(containingTypeObj) ? result : null;
            result = MetadataUpdatableParser.Create(containingTypeObj, ParserFactory, initialParser);
            CharParser<T?> ParserFactory()
            {
                var builderOptions = new BuilderOptions();
                // Extract build options from the attribute; it should always exist, unless this method was manually
                // called. We have to get the attribute every time, because it might have changed in the reload.
                if (precompilerInputFunction.Method.GetCustomAttribute<PrecompilerInputAttribute>() is { } attr)
                {
                    builderOptions.UpdateFrom(attr);
                }
                var builder = precompilerInputFunction();
                return builder.BuildSyntaxCheck<T>(builderOptions);
            }
        }

        return result;
    }

    /// <summary>
    /// Returns a COM# object that implements the precompiler interface.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Most of the precompiler is implemented in the <c>Farkle</c> assembly, and part of it in
    /// <c>Farkle.Tools.MSBuild</c> (known as the <i>precompiler host</i>). The precompiler interface is the
    /// contract between the Farkle library and the precompiler host.
    /// </para>
    /// <para>
    /// This method gets called by the precompiler host via reflection. The COM# interfaces implemented by the
    /// returned object are an implementation detail that can change at any time, and should not be used by
    /// third-party code. This method's return type might also change in the future.
    /// </para>
    /// </remarks>
    [RequiresUnreferencedCode(PrecompilerImplementation.RequiresUnreferencedCodeMessage)]
    internal static ComSharpObject GetPrecompilerInterface() =>
        PrecompilerInterfaceWrappers.Instance.ConvertToComSharp(new PrecompilerImplementation());
}
