<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="../../src/Farkle.Tools.MSBuild/build/Farkle.Tools.MSBuild.props" />
  <Import Project="../../eng/integration-test-setup.props" />
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <FarkleGenerateHtml>true</FarkleGenerateHtml>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Farkle/Farkle.csproj" />
    <ProjectReference Include="../../src/Farkle.Tools.MSBuild/Farkle.Tools.MSBuild.fsproj" ReferenceOutputAssembly="false" />
    <PackageReference Include="Sigourney.Build" />
    <PackageReference Include="HtmlAgilityPack" />
    <PackageReference Include="Microsoft.Data.SqlClient" />
    <PackageReference Include="NUnit" />
    <PackageReference Include="NUnit3TestAdapter" />
    <PackageReference Include="NUnit.Analyzers" PrivateAssets="all" />
  </ItemGroup>

  <Import Project="../../src/Farkle.Tools.MSBuild/build/Farkle.Tools.MSBuild.targets" />
</Project>
