<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="../../src/Farkle.Tools.MSBuild/build/Farkle.Tools.MSBuild.props" />
  <Choose>
    <When Condition="$(MSBuildRuntimeType) == Core OR ('$(MSBuildVersion)' != '' AND $([System.Version]::Parse($(MSBuildVersion)).Major) &gt;= 18)">
      <PropertyGroup>
        <FarkleTaskAssembly>$(MSBuildThisFileDirectory)../../src/Farkle.Tools.MSBuild/bin/$(Configuration)/net8.0/Farkle.Tools.MSBuild.dll</FarkleTaskAssembly>
      </PropertyGroup>
    </When>
    <Otherwise>
      <PropertyGroup>
        <FarkleTaskAssembly>$(MSBuildThisFileDirectory)../../src/Farkle.Tools.MSBuild/bin/$(Configuration)/netstandard2.0/Farkle.Tools.MSBuild.dll</FarkleTaskAssembly>
      </PropertyGroup>
    </Otherwise>
  </Choose>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <FarkleGenerateHtml>true</FarkleGenerateHtml>
    <!-- Load the precompiler tasks in a separate (ephemeral) process, to avoid locking the assembly
    files during development. -->
    <FarklePrecompilerTaskFactory>TaskHostFactory</FarklePrecompilerTaskFactory>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Farkle/Farkle.csproj" />
    <ProjectReference Include="../../src/Farkle.Tools.MSBuild/Farkle.Tools.MSBuild.fsproj" ReferenceOutputAssembly="false" />
    <PackageReference Include="Sigourney.Build" />
    <PackageReference Include="HtmlAgilityPack" />
    <PackageReference Include="Microsoft.Data.SqlClient" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Microsoft.Testing.Extensions.VSTestBridge" />
    <PackageReference Include="Microsoft.Testing.Platform.MSBuild" />
    <PackageReference Include="NUnit" />
    <PackageReference Include="NUnit3TestAdapter" />
    <PackageReference Include="NUnit.Analyzers" PrivateAssets="all" />
  </ItemGroup>

  <Import Project="../../src/Farkle.Tools.MSBuild/build/Farkle.Tools.MSBuild.targets" />
</Project>
