<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="../NuGet.props" />
  <PropertyGroup>
    <TargetFrameworks>net8.0;netstandard2.0</TargetFrameworks>
    <Description>Farkle's integration with MSBuild. Using this package on a project will precompile its grammars ahead of time when it is built.</Description>
    <PackageTags>$(PackageTags);msbuild;sigourney</PackageTags>
    <DevelopmentDependency>true</DevelopmentDependency>
    <DisableImplicitFSharpCoreReference>true</DisableImplicitFSharpCoreReference>
    <PatchNuspecDependencies>true</PatchNuspecDependencies>
    <NoWarn>$(NoWarn);NU5128</NoWarn>
  </PropertyGroup>
  <PropertyGroup>
    <GenerateDependencyFile>true</GenerateDependencyFile>
    <TargetsForTfmSpecificBuildOutput>$(TargetsForTfmSpecificBuildOutput);CopyProjectReferencesToPackage</TargetsForTfmSpecificBuildOutput>
    <BuildOutputTargetFolder>tools</BuildOutputTargetFolder>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="MSBuildAttributes.fs" />
    <Compile Include="Logging.fs" />
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFrameworkIdentifier)' == '.NETCoreApp'">
    <Compile Include="../Farkle/Farkle.fs" />
    <Compile Include="FarklePrecompilerTask.fs" />
    <Compile Include="FarkleGenerateHtml.fs" />
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFrameworkIdentifier)' != '.NETCoreApp'">
    <Compile Include="FarklePrecompilerTask.Dummy.fs" />
    <Compile Include="FarkleGenerateHtml.Dummy.fs" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="build/**" Pack="true" PackagePath="build" />
    <EmbeddedResource Update="Properties/*.resx" ManifestResourceName="Farkle.Tools.MSBuild.%(Filename)" />
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFrameworkIdentifier)' == '.NETCoreApp'">
    <ProjectReference Include="..\Farkle\Farkle.csproj" PrivateAssets="all" />
    <ProjectReference Include="..\Farkle.Tools.Shared\Farkle.Tools.Shared.fsproj" PrivateAssets="all" />
    <ProjectReference Include="..\Farkle.Tools.Precompiler\Farkle.Tools.Precompiler.csproj" PrivateAssets="all" />
    <!-- Include all exported dependencies here. A task will remove the framework attribute from the nuspec. -->
    <PackageReference Include="Sigourney.Build" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="FSharp.Core" PrivateAssets="all" />
    <PackageReference Include="Serilog.Sinks.MSBuild" PrivateAssets="all" />
    <PackageReference Include="Sigourney" PrivateAssets="all" />
  </ItemGroup>
  <Target
      Name="AddBuildDependencyFileToBuiltProjectOutputGroupOutput"
      BeforeTargets="BuiltProjectOutputGroup">
    <ItemGroup>
      <BuiltProjectOutputGroupOutput
        Include="$(ProjectDepsFilePath)"
        TargetPath="$(ProjectDepsFileName)"
        FinalOutputPath="$(ProjectDepsFilePath)" />
    </ItemGroup>
  </Target>
  <Target
    Name="CopyProjectReferencesToPackage"
    DependsOnTargets="ResolveReferences">
    <ItemGroup>
        <BuildOutputInPackage
            Include="@(ReferenceCopyLocalPaths)"
            TargetPath="%(ReferenceCopyLocalPaths.DestinationSubPath)" />
    </ItemGroup>
  </Target>
</Project>
