// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Farkle")>]
[<assembly: AssemblyProductAttribute("Farkle")>]
[<assembly: AssemblyDescriptionAttribute("A LALR parsing toolkit for F#.")>]
[<assembly: AssemblyVersionAttribute("0.0.1")>]
[<assembly: AssemblyFileVersionAttribute("0.0.1")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Farkle"
    let [<Literal>] AssemblyProduct = "Farkle"
    let [<Literal>] AssemblyDescription = "A LALR parsing toolkit for F#."
    let [<Literal>] AssemblyVersion = "0.0.1"
    let [<Literal>] AssemblyFileVersion = "0.0.1"
    let [<Literal>] AssemblyConfiguration = "Release"
