<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="../NuGet.props" />
  <PropertyGroup>
    <!-- <TargetFrameworks>net10.0;net8.0;netstandard2.0;netstandard2.1</TargetFrameworks> -->
    <TargetFrameworks>net10.0;net8.0</TargetFrameworks>
    <LangVersion>14</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Nullable Condition="'$(TargetFramework)' == 'netstandard2.0'">annotations</Nullable>
    <IsAotCompatible Condition="$([MSBuild]::GetTargetFrameworkIdentifier('$(TargetFramework)')) == '.NETCoreApp'">true</IsAotCompatible>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <RootNamespace>Farkle</RootNamespace>
    <PolySharpIncludeRuntimeSupportedAttributes>true</PolySharpIncludeRuntimeSupportedAttributes>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../Common/ComSharp/**/*.cs" LinkBase="ComSharp" />
    <Content Include="Farkle.fs" Pack="true" PackagePath="contentFiles/fs/any" BuildAction="Compile" />
    <Content Include="Farkle.fsx" Pack="true" PackagePath="content" />
    <InternalsVisibleTo Include="Farkle.Benchmarks" />
    <InternalsVisibleTo Include="Farkle.Tests" />
    <InternalsVisibleTo Include="Farkle.Tests.CSharp" />
    <PackageReference Include="DotNet.ReproducibleBuilds" PrivateAssets="all" />
    <PackageReference Include="PolySharp" PrivateAssets="all" />
    <PackageReference Include="BitCollections" />
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFrameworkIdentifier)' != '.NETCoreApp'">
    <PackageReference Include="System.Collections.Immutable" />
  </ItemGroup>
  <ItemGroup Condition="!$([MSBuild]::IsTargetFrameworkCompatible($(TargetFramework), 'netstandard2.1'))">
    <PackageReference Include="Microsoft.Bcl.HashCode" />
    <PackageReference Include="System.Buffers" />
    <PackageReference Include="System.Memory" />
    <PackageReference Include="System.Threading.Tasks.Extensions" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Update="Properties/*.resx" ManifestResourceName="Farkle.%(Filename)" />
    <EmbeddedResource Include="ILLink.Substitutions.xml" LogicalName="ILLink.Substitutions.xml" />
  </ItemGroup>
</Project>
