<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="../NuGet.props" />
  <PropertyGroup>
    <TargetFrameworks>net10.0;net8.0</TargetFrameworks>
    <LangVersion>14</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Nullable Condition="'$(TargetFramework)' == 'netstandard2.0'">annotations</Nullable>
    <IsAotCompatible Condition="$([MSBuild]::GetTargetFrameworkIdentifier('$(TargetFramework)')) == '.NETCoreApp'">true</IsAotCompatible>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <RootNamespace>Farkle</RootNamespace>
    <PolySharpIncludeRuntimeSupportedAttributes>true</PolySharpIncludeRuntimeSupportedAttributes>
    <Description>Farkle is a .NET library for building fast, reliable LR(1) text parsers in C# and F#.</Description>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <EnablePackageValidation>true</EnablePackageValidation>
    <PackageValidationBaselineVersion>7.0.1</PackageValidationBaselineVersion>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../Common/ComSharp/**/*.cs" LinkBase="ComSharp" />
    <!-- Use the earliest supported framework. We can't use "any", because the package would be installable
    even on frameworks we don't provide binaries for. -->
    <Content Include="Farkle.fs" Pack="true" PackagePath="contentFiles/fs/net8.0" BuildAction="Compile" />
    <Content Include="Farkle.fsx" Pack="true" PackagePath="content" />
    <None Include="README.md" Pack="true" PackagePath="\" />
    <None Include="../Farkle.Analyzers/bin/$(Configuration)/netstandard2.0/Farkle.Analyzers.dll" Pack="true" PackagePath="analyzers/dotnet/cs" Visible="false" />
    <InternalsVisibleTo Include="Farkle.Benchmarks" />
    <InternalsVisibleTo Include="Farkle.Tests" />
    <InternalsVisibleTo Include="Farkle.Tests.CSharp" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="DotNet.ReproducibleBuilds" PrivateAssets="all" />
    <PackageReference Include="PolySharp" PrivateAssets="all" />
    <PackageReference Include="BitCollections" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Farkle.Analyzers\Farkle.Analyzers.csproj" ReferenceOutputAssembly="false" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Update="Properties/*.resx" ManifestResourceName="Farkle.%(Filename)" />
    <EmbeddedResource Include="ILLink.Substitutions.xml" LogicalName="ILLink.Substitutions.xml" />
  </ItemGroup>
</Project>
