<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net10.0</TargetFrameworks>
    <LangVersion>14</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsRoslynComponent>true</IsRoslynComponent>
    <EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../Farkle/Compatibility/Compatibility.cs" Link="Compatibility\Compatibility.cs" />
    <Compile Include="../Farkle/Compatibility/HashCode.cs" Link="Compatibility\HashCode.cs" />
    <Compile Include="../Farkle/Compatibility/Enumerable.cs" Link="Compatibility\Enumerable.cs" />
    <Compile Include="../Common/Roslyn/EquatableArray.cs" Link="Common\Roslyn\EquatableArray.cs" />
    <Compile Include="../Common/Roslyn/IncrementalGeneratorContextExtensions.cs" Link="Common\Roslyn\IncrementalGeneratorContextExtensions.cs" />
    <Using Include="Common" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" />
    <PackageReference Include="PolySharp" PrivateAssets="all" />
  </ItemGroup>
  <ItemGroup>
    <!-- Include embedded sources in design-time builds to get IntelliSense. They use some features not available in .NET Standard 2.0. -->
    <Compile Condition="$(DesigntimeBuild) == false OR '$(TargetFramework)' == 'netstandard2.0'" Remove="EmbeddedSources/**" />
    <EmbeddedResource Include="EmbeddedSources/**.cs" LogicalName="EmbeddedSources.%(Filename)" />
  </ItemGroup>
</Project>
