// Copyright © Theodore Tsirpanis and Contributors.
// SPDX-License-Identifier: MIT

using Microsoft.CodeAnalysis;

namespace Farkle.Analyzers;

internal static partial class Compatibility
{
    extension(IncrementalGeneratorPostInitializationContext context)
    {
        // TODO-NET8: Remove when we update to Roslyn 5.x
        public void AddEmbeddedAttributeDefinition()
        {
            context.AddSource("Microsoft.CodeAnalysis.EmbeddedAttribute",
            // lang=C#
            """
            // <auto-generated/>
            namespace Microsoft.CodeAnalysis
            {
                internal sealed partial class EmbeddedAttribute : global::System.Attribute
                {
                }
            }
            """);
        }
    }
}
