// Copyright © Theodore Tsirpanis and Contributors.
// SPDX-License-Identifier: MIT

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Testing;
using Microsoft.CodeAnalysis.Diagnostics;

namespace Farkle.Analyzers.Tests;

public sealed class FarkleAnalyzerTest<TAnalyzer> : CSharpAnalyzerTest<TAnalyzer, NUnitVerifier>
    where TAnalyzer : DiagnosticAnalyzer, new()
{
    private static readonly MetadataReference? s_farkleReference =
        MetadataReference.TryCreateFromRawMetadata(typeof(Builder.IGrammarSymbol).Assembly);

    public FarkleAnalyzerTest()
    {
        if (s_farkleReference is null)
        {
            Assert.Inconclusive("Could not create a metadata reference for the Farkle assembly.");
        }

        TestState.OutputKind = OutputKind.ConsoleApplication; // Allow top-level statements.
        // We cannot bring the source generator, because the analyzer runs before it, so we need to
        // provide a skeleton of the post-initialization-generated code manually.
        // lang=c#
        TestState.Sources.Add("""
        // <auto-generated/>

        global using Farkle.Builder;

        using System;

        namespace Farkle.Builder;

        [AttributeUsage(AttributeTargets.All, AllowMultiple = true)]
        internal partial class UseEnhancedSyntaxAttribute : Attribute;

        internal static partial class Production
        {
            public static ProductionBuilder Create(params ReadOnlySpan<object> members) => new(members);
        }

        """);
        TestState.AdditionalReferences.Add(s_farkleReference);
    }
}
