// Copyright © Theodore Tsirpanis and Contributors.
// SPDX-License-Identifier: MIT

using Farkle.Analyzers.EnhancedSyntax;

namespace Farkle.Analyzers.Tests;

public class ProductionBuilderFactoryGeneratorTests
{
    [Test]
    public async Task TestHappyPath()
    {
        var test = new VerifyCS();
        test.TestState.Sources.Add(/*lang=C#*/ """
            using Farkle.Builder;

            [module: UseEnhancedSyntax]

            string str = null;
            IGrammarSymbol<int> symbol = null;
            IGrammarSymbol symbolU = null;

            _ = Production.Build(str, symbol, symbolU);
            _ = Production.Build(str, str, str);
            _ = Production.Build(symbol, symbol, symbol);
            _ = Production.Build(symbol, symbolU, symbolU);
            """);
        test.TestState.GeneratedSources.Add((typeof(ProductionBuilderFactoryGenerator), "Production.g.cs", /*lang=C#*/ """
            // <auto-generated/>

            #nullable enable

            namespace Farkle.Builder;

            internal static partial class Production
            {
                public static ProductionBuilder Build(string member1, string member2, string member3) =>
                    Runtime.ProductionBuilderMarshal.Create<ProductionBuilder>([Terminal.Literal(member1), Terminal.Literal(member2), Terminal.Literal(member3)], []);

                public static ProductionBuilders.ProductionBuilder<T1> Build<T1>(IGrammarSymbol<T1> member1, IGrammarSymbol member2, IGrammarSymbol member3) =>
                    Runtime.ProductionBuilderMarshal.Create<ProductionBuilders.ProductionBuilder<T1>>([member1, member2, member3], [0]);

                public static ProductionBuilders.ProductionBuilder<T1> Build<T1>(string member1, IGrammarSymbol<T1> member2, IGrammarSymbol member3) =>
                    Runtime.ProductionBuilderMarshal.Create<ProductionBuilders.ProductionBuilder<T1>>([Terminal.Literal(member1), member2, member3], [1]);

                public static ProductionBuilders.ProductionBuilder<T1, T2, T3> Build<T1, T2, T3>(IGrammarSymbol<T1> member1, IGrammarSymbol<T2> member2, IGrammarSymbol<T3> member3) =>
                    Runtime.ProductionBuilderMarshal.Create<ProductionBuilders.ProductionBuilder<T1, T2, T3>>([member1, member2, member3], [0, 1, 2]);
            }

            """));
        await test.RunAsync();
    }

    [Test]
    public async Task TestNoProductionFactories()
    {
        var test = new VerifyCS();
        test.TestState.Sources.Add(/*lang=C#*/ """
            using Farkle.Builder;

            string str = null;
            IGrammarSymbol<int> symbol = null;
            IGrammarSymbol symbolU = null;

            _ = str.Appended().Append(symbol).Append(symbolU);
            _ = str.Appended().Append(str).Append(str);
            _ = symbol.Extended().Extend(symbol).Extend(symbol);
            _ = symbol.Extended().Append(symbolU).Append(symbolU);
            """);
        await test.RunAsync();
    }
}

file sealed class VerifyCS : FarkleSourceGeneratorTest<ProductionBuilderFactoryGenerator>
{
    public VerifyCS()
    {
        TestState.GeneratedSources.Add((typeof(ProductionBuilderFactoryGenerator), "Microsoft.CodeAnalysis.EmbeddedAttribute.cs", /*lang=C#*/ """
            // <auto-generated/>
            namespace Microsoft.CodeAnalysis
            {
                internal sealed partial class EmbeddedAttribute : global::System.Attribute
                {
                }
            }
            """));
        TestState.GeneratedSources.Add((typeof(ProductionBuilderFactoryGenerator), ProductionBuilderFactoryGenerator.ProductionBoilerplateName, ProductionBuilderFactoryGenerator.ProductionBoilerplateSource));
        TestState.GeneratedSources.Add((typeof(ProductionBuilderFactoryGenerator), ProductionBuilderFactoryGenerator.UseEnhancedSyntaxAttributeBoilerplateName, ProductionBuilderFactoryGenerator.UseEnhancedSyntaxAttributeBoilerplateSource));
    }
}
