// Copyright © Theodore Tsirpanis and Contributors.
// SPDX-License-Identifier: MIT

using System.Reflection;
using System.Reflection.Metadata;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Testing;

namespace Farkle.Analyzers.Tests;

public static class Utilities
{
    public static readonly MetadataReference? FarkleReference =
        MetadataReference.TryCreateFromRawMetadata(typeof(Builder.IGrammarSymbol).Assembly);

    // We cannot bring the source generator, because the analyzer runs before it, so we need to
    // provide a skeleton of the post-initialization-generated code manually.
    // lang=C#
    public const string EnhancedSyntaxBoilerplate = """
        // <auto-generated/>

        global using Farkle.Builder;

        using System;

        namespace Farkle.Builder;

        [AttributeUsage(AttributeTargets.All, AllowMultiple = true)]
        internal partial class UseEnhancedSyntaxAttribute : Attribute;

        internal static partial class Production
        {
            public static ProductionBuilder Create(params object[] members) => new(members);
        }

        """;

    extension(MetadataReference)
    {
        public static MetadataReference? TryCreateFromRawMetadata(Assembly assembly)
        {
            unsafe
            {
                if (!assembly.TryGetRawMetadata(out var blob, out var blobLength))
                {
                    return null;
                }
                var moduleMd = ModuleMetadata.CreateFromMetadata((IntPtr)blob, blobLength, () => GC.KeepAlive(assembly));
                var assemblyMd = AssemblyMetadata.Create(moduleMd);
                return assemblyMd.GetReference(filePath: assembly.Location, display: assembly.FullName);
            }
        }
    }

    extension<TVerify>(AnalyzerTest<TVerify> test) where TVerify : IVerifier, new()
    {
        public void CommonInitialize()
        {
            if (FarkleReference is null)
            {
                Assert.Inconclusive("Could not create a metadata reference for the Farkle assembly.");
            }

            test.TestState.OutputKind = OutputKind.ConsoleApplication; // Allow top-level statements.
            test.TestState.AdditionalReferences.Add(FarkleReference);
        }
    }
}
