name: Benchmark

on:
  push:
    tags:
      - '*'
  workflow_dispatch:
    inputs:
      args:
        description: 'Arguments to pass to the benchmark program'
        default: '-f * --memory true -e github json'
        required: true

permissions: read-all

env:
  FARKLE_BENCHMARK_ARGS: ${{ github.event.inputs.args }}

jobs:
  benchmark:
    name: Benchmark
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
          dotnet-quality: preview
      - name: Restore .NET local tools
        run: dotnet tool restore
      - name: Run benchmarks
        run: dotnet run --project eng/Farkle.Build.fsproj -- -t Benchmark
