name: CI

on:
  push:
    branches:
      - mainstream
      - release/*
  pull_request:
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'

jobs:
  test:
    name: Test
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up .NET SDK from global.json
        uses: actions/setup-dotnet@v3
      - name: Restore .NET local tools
        run: dotnet tool restore
      - name: Run tests
        run: dotnet run --project eng/Farkle.Build.fsproj -- -t Test
