name: Release

on:
  push:
    branches:
      - mainstream
      - release/*
  release:
    types: [published]

permissions: read-all

jobs:
  pack:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v5
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      - name: Restore .NET local tools
        run: dotnet tool restore
      - name: Pack
        run: dotnet run --project eng/Farkle.Build.fsproj -- -t NuGetPack
      - name: Upload package artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nuget-packages
          path: ./bin
  release:
    needs: pack
    environment: ${{ github.event_name == 'release' && 'release' || 'nightly' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v5
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      - name: Download package artifacts
        uses: actions/download-artifact@v5
        with:
          name: nuget-packages
          path: ./bin
      - name: Publish
        run: dotnet nuget push ./bin/*.nupkg --api-key ${{ secrets.NUGET_KEY }} --source ${{ vars.NUGET_FEED }}
