name: Release

on:
  push:
    branches:
      - mainstream
      - release/*
  release:
    types: [published]

permissions: read-all

jobs:
  pack:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v6
      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x
      - name: Restore .NET local tools
        run: dotnet tool restore
      - name: Pack
        run: dotnet run --project eng/Farkle.Build.fsproj -- -t NuGetPack
      - name: Upload package artifacts
        uses: actions/upload-artifact@v6
        with:
          name: nuget-packages
          path: ./bin
  release:
    needs: pack
    environment: ${{ github.event_name == 'release' && 'release' || 'nightly' }}
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v6
      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x
      - name: Obtain NuGet API token
        uses: nuget/login@v1
        id: nuget-login
        with:
          user: ${{ vars.NUGET_USER }}
        if: vars.NUGET_USER != ''
      - name: Download package artifacts
        uses: actions/download-artifact@v8
        with:
          name: nuget-packages
          path: ./bin
      - name: Publish
        run: dotnet nuget push ./bin/*.nupkg --api-key ${{ steps.nuget-login.outputs.NUGET_API_KEY || secrets.NUGET_KEY }} --source ${{ vars.NUGET_FEED }}
