// <auto-generated/>

#nullable enable

using Microsoft.CodeAnalysis;

namespace ComSharp;

/// <summary>
/// Specifies across which directions to generate wrappers for a COM# interface.
/// </summary>
[Embedded]
[Flags]
internal enum ComSharpInterfaceOptions
{
    /// <summary>
    /// Generate wrappers from .NET to COM#.
    /// </summary>
    ComSharpWrapper = 1,
    /// <summary>
    /// Generate wrappers from COM# to .NET.
    /// </summary>
    DotNetWrapper = 2,
    /// <summary>
    /// Generate wrappers across both directions between .NET and COM#.
    /// </summary>
    Both = ComSharpWrapper | DotNetWrapper,
}
