// <auto-generated/>

#nullable enable

using Microsoft.CodeAnalysis;

namespace ComSharp;

[Embedded]
[AttributeUsage(AttributeTargets.Class, AllowMultiple = true)]
internal sealed class GenerateComSharpWrappersAttribute(Type type) : Attribute
{
    public Type Type { get; } = type;

    public ComSharpInterfaceOptions Options { get; set; } = ComSharpInterfaceOptions.ComSharpWrapper | ComSharpInterfaceOptions.DotNetWrapper;
}
