<Project Sdk="Microsoft.NET.Sdk">
  <!-- Test the dummy Farkle.Tools.MSBuild package this way, without having to set up the whole infrastructure now. -->
  <Import Project="../../src/Farkle.Tools.MSBuild/build/dummy/Farkle.Tools.MSBuild.props" />
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <!-- Using "new" to create disposable types. -->
    <NoWarn>$(NoWarn);FS0760</NoWarn>
    <GenerateProgramFile>false</GenerateProgramFile>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../../src/Farkle/Farkle.fs"/>
    <Compile Include="Common.fs" />
    <!-- <Compile Include="GOLDParserBridge.fs" /> -->
    <Compile Include="Generators.fs" />
    <!-- The test source files do not depend on each other, so why not? -->
    <Compile Include="./*Tests.fs" />
    <Content Include="../resources/**" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Testing.Extensions.VSTestBridge" />
    <ProjectReference Include="..\..\src\Farkle\Farkle.csproj" />
    <ProjectReference Include="..\..\sample\Farkle.Samples.CSharp\Farkle.Samples.CSharp.csproj" />
    <ProjectReference Include="..\..\sample\Farkle.Samples.FSharp\Farkle.Samples.FSharp.fsproj" />
    <PackageReference Include="Expecto" />
    <PackageReference Include="Expecto.FsCheck" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="YoloDev.Expecto.TestSdk" />
  </ItemGroup>
</Project>
